def pipeline {
    agent any

    stages {
        stage ('github-clone'){
            steps {
                git branch : 'main', credentialsId "GitHub_Token", url : '{https://github.com/JaeToi/SonarGit.git}'
            }
        }
    }
}