pipeline {
    agent any

    stages {
        stage('build'){
            steps{
                build wait: false, job: 'GitHub_Project', waitForStart: true
            }
        }
        stage ('checkout'){
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'GitHub_Token', url: 'https://github.com/JaeToi/SonarGit.git']])
            }
        }
  

          stage('SCM') {
            steps {
                checkout scm
            }
          }
          stage('SonarQube Analysis') {
            steps {
           
                withSonarQubeEnv('SonarQube-Server') {
                  sh "C:\sonarqube-10.5.1.90531\sonar-scanner-cli-5.0.1.3006-windows\sonar-scanner-5.0.1.3006-windows\bin"
                }
            }
          }
  }
}
