on:
  # schedule:
    # - cron: '0 * * * 1'
  workflow_dispatch:

name: SonarQube Workflow
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: 
          fetch-length:  0   # 더 나은 분석 관련성을 위해 얕은 클론을 비활성화해야 합니다. 
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/classes

  sonarQube:
    needs: build
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        SONAR_TOKEN: ${{ secrets.SONAR_HOST }}
        SONAR_HOST_URL: ${{ secrets.SONAR_TOKEN }}
